# Generated by Django 4.0.4 on 2022-04-15 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Password',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(blank=True, max_length=100, verbose_name='password')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='date of creation')),
                ('validity_period', models.IntegerField(blank=True, choices=[(6, 'six months'), (12, 'one year')], null=True, verbose_name='password validity')),
            ],
        ),
    ]
